server:
  ssh:
    host: 192.168.4.2
    port: 2223
    user: ubuntu
    pass: root

  sudo_password: root
  ssl: false
  name: nestjs-boilerplate

  services:
    backend:
      type: nestjs
      domain: 192.168.4.2
      repository: https://github.com/SojebSikder/nestjs-boilerplate.git
      port: 4000