server:
  ssh:
    host: 192.168.4.2
    port: 2223
    user: ubuntu
    pass: root

  sudo_password: root
  ssl: true
  name: blog

  services:
    backend:
      type: nestjs
      domain: test.com
      port: 4000
    frontend:
      type: nextjs
      domain: test.com
      port: 3000
